### ISSUE TITLE
Support django >= 2.0

### ISSUE THREAD

**Issue by jnoortheen** [ashchristopher/django-pgcli#8]
Add support to Django versions 1.11 <= 2.0

**Comment by ddimmich** [comment]
See https://github.com/ashchristopher/django-pgcli/pull/9 - seems to work out of the box.

**Comment by mnieber** [comment]
You can use a work-around and install the fork of @jnoortheen by using this in your `requirements.txt` instead of `django-pgcli`

```
git+git://github.com/jnoortheen/django-pgcli@master#egg=django-pgcli
```
